In [1]:
import pandas as pd
df = pd.read_csv('M2M_hware_classroom.csv')
df.head(15)

,Meeting Location,Unnamed: 1,OSS 318,OSS 333,OSS 313,OSS LL18,OSS LL13,OWS 275,OSS LL14,OSS 230,...,OSS LL10,OSS LL15,OSS LL17,OSS LL19,FDC 212,FDC 213,FDC 214,BIN LL02,BIN LL02A,FDC 307
0,ID,ID,5,6,7,8,9,10,11,12,...,34,35,36,37,38,39,40,41,42,43
1,Projector Screen,1,1,1,1,0,1,0,1,1,...,1,1,0,1,0,0,0,0,0,0
2,Projector,2,1,1,1,0,1,0,0,1,...,1,1,0,1,0,0,0,0,0,0
3,Web Camera,3,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
4,Microphone,4,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,Speakers,5,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,Hovercam,6,1,1,1,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
7,White Board,7,1,1,1,0,1,0,1,1,...,1,1,1,1,0,0,0,0,0,0
8,Black Board,8,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
9,Podium,9,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,Printer,10,0,1,0,0,1,0,0,0,...,1,0,0,1,0,0,0,0,0,0
11,Phone,11,1,1,0,0,0,0,1,1,...,1,1,1,0,0,0,0,0,0,0
12,TV - Flat Panel,12,0,0,0,0,0,0,0,0,...,0,0,1,0,0,0,0,0,0,0
13,Transparency Projector,13,0,1,1,0,0,0,0,0,...,0,1,0,0,0,0,0,0,0,0

In [2]:
df['OSS 318'][0]

5

In [3]:
for colm in df.columns:
    df.loc[df[colm] == 1, colm] = df[colm][0]

df.head(20)

,Meeting Location,Unnamed: 1,OSS 318,OSS 333,OSS 313,OSS LL18,OSS LL13,OWS 275,OSS LL14,OSS 230,...,OSS LL10,OSS LL15,OSS LL17,OSS LL19,FDC 212,FDC 213,FDC 214,BIN LL02,BIN LL02A,FDC 307
0,ID,ID,5,6,7,8,9,10,11,12,...,34,35,36,37,38,39,40,41,42,43
1,Projector Screen,1,5,6,7,0,9,0,11,12,...,34,35,0,37,0,0,0,0,0,0
2,Projector,2,5,6,7,0,9,0,0,12,...,34,35,0,37,0,0,0,0,0,0
3,Web Camera,3,0,0,0,0,0,0,0,12,...,0,0,0,0,0,0,0,0,0,0
4,Microphone,4,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,Speakers,5,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
6,Hovercam,6,5,6,7,0,0,0,0,12,...,0,0,0,0,0,0,0,0,0,0
7,White Board,7,5,6,7,0,9,0,11,12,...,34,35,36,37,0,0,0,0,0,0
8,Black Board,8,0,0,0,0,0,0,0,12,...,0,0,0,0,0,0,0,0,0,0
9,Podium,9,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,Printer,10,0,6,0,0,9,0,0,0,...,34,0,0,37,0,0,0,0,0,0
11,Phone,11,5,6,0,0,0,0,11,12,...,34,35,36,0,0,0,0,0,0,0
12,TV - Flat Panel,12,0,0,0,0,0,0,0,0,...,0,0,36,0,0,0,0,0,0,0
13,Transparency Projector,13,0,6,7,0,0,0,0,0,...,0,35,0,0,0,0,0,0,0,0

In [4]:
df = df.iloc[1:]

In [5]:
df.head()

,Meeting Location,Unnamed: 1,OSS 318,OSS 333,OSS 313,OSS LL18,OSS LL13,OWS 275,OSS LL14,OSS 230,...,OSS LL10,OSS LL15,OSS LL17,OSS LL19,FDC 212,FDC 213,FDC 214,BIN LL02,BIN LL02A,FDC 307
1,Projector Screen,1,5,6,7,0,9,0,11,12,...,34,35,0,37,0,0,0,0,0,0
2,Projector,2,5,6,7,0,9,0,0,12,...,34,35,0,37,0,0,0,0,0,0
3,Web Camera,3,0,0,0,0,0,0,0,12,...,0,0,0,0,0,0,0,0,0,0
4,Microphone,4,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
5,Speakers,5,5,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [18]:
df_out = pd.DataFrame(columns=['clas_hware_id', 'classroom_id'])
df2 = pd.DataFrame(columns=['clas_hware_id', 'classroom_id'])

In [16]:
df.columns

Index(['Meeting Location', 'Unnamed: 1', 'OSS 318', 'OSS 333', 'OSS 313',
       'OSS LL18', 'OSS LL13', 'OWS 275', 'OSS LL14', 'OSS 230', 'OSS 328',
       'OSS 120', 'OSS 121', 'OSS 122', 'OSS 123', 'OSS 124', 'OSS 127',
       'OSS 214', 'OSS 226', 'OSS 227', 'OSS 236', 'OSS 325', 'OSS 326',
       'OSS 327', 'OSS 329', 'OSS 428', 'OSS 431', 'OSS 432', 'OSS 434',
       'OSS 435', 'OSS LL06', 'OSS LL10', 'OSS LL15', 'OSS LL17', 'OSS LL19',
       'FDC 212', 'FDC 213', 'FDC 214', 'BIN LL02', 'BIN LL02A', 'FDC 307'],
      dtype='object')

In [19]:
for colm in ['OSS 318', 'OSS 333', 'OSS 313',
       'OSS LL18', 'OSS LL13', 'OWS 275', 'OSS LL14', 'OSS 230', 'OSS 328',
       'OSS 120', 'OSS 121', 'OSS 122', 'OSS 123', 'OSS 124', 'OSS 127',
       'OSS 214', 'OSS 226', 'OSS 227', 'OSS 236', 'OSS 325', 'OSS 326',
       'OSS 327', 'OSS 329', 'OSS 428', 'OSS 431', 'OSS 432', 'OSS 434',
       'OSS 435', 'OSS LL06', 'OSS LL10', 'OSS LL15', 'OSS LL17', 'OSS LL19',
       'FDC 212', 'FDC 213', 'FDC 214', 'BIN LL02', 'BIN LL02A', 'FDC 307']:
    df2[['clas_hware_id', 'classroom_id']] = df[['Unnamed: 1', colm]]
    df_out = df_out.append(df2, ignore_index=True)
    
df_out.head(10)

  clas_hware_id classroom_id
0             1            5
1             2            5
2             3            0
3             4            5
4             5            5
5             6            5
6             7            5
7             8            0
8             9            0
9            10            0

In [22]:
df_out_1 = df_out[df_out["classroom_id"] != 0]

In [28]:
df_out_1.to_csv("M2M_hware_classroom_up.csv", index=False)